### ISSUE TITLE
Map / Disabling mousewheel

### ISSUE THREAD

**Issue by nelsonmau** [ondata/confiscatibene-emiliaromagna#2]
@gian-ppp nella tua mappa fatta su cartodb, puoi disabilitare il `mousewheel` ?

Il motivo è: se provi  fare scroll down / scroll up nella pagina online emiliaromagna.confiscatibene.it, invece di scrollare sulla pagina, si fa zoom+ / zoom-  sulla mappa
(non sono certo di essermi spiegato per bene)

**Comment by gian-ppp** [comment]
Opzione mousewheel disattivata, ho controllato e ora nel sito dovrebbe
andare tutto bene.

Il giovedì 12 maggio 2016, Andrea Nelson Mauro notifications@github.com
ha scritto:

**Comment by nelsonmau** [comment]
ottimo @gian-ppp, però credo per errore tu abbia modificato lo zoom, prova tu stesso a dare un'occhiata qui http://emiliaromagna.confiscatibene.it/
riesci a sistemarlo? grazie! :)

**Comment by gian-ppp** [comment]
Nel senso di attivo o disattivo?

Fixed

**Comment by nelsonmau** [comment]
nono, scusami mi sono espresso male. Quello zoom va tenuto attivo (sennò l'utente non può zoomare). Quello che intendo è che mentre modificafi hai fatto forse zoom out. Se vedi, adesso l'emilia adesso non è al centro ed è molto piccolina

spero di averlo detto bene adesso 

![cb_er1](https://cloud.githubusercontent.com/assets/1769578/15214774/4b8cfa42-184f-11e6-9aa1-d1d630671ad6.png)

**Comment by gian-ppp** [comment]
Spero di aver sistemato, grazie delle delucidazione

**Comment by nelsonmau** [comment]
It works!
grazie a te, mi ero spiegato male io!
chiudo questa issue allora :)
